### ISSUE TITLE
Add support for safari?

### ISSUE THREAD

**Issue by qiangbro** [probil/vue-prevent-unload#1]
As we know, Safari does not support beforeunload Event, so this component doesn't work on ios.
see: [https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/HandlingEvents/HandlingEvents.html#//apple_ref/doc/uid/TP40006511-SW5](url)

Do you have plan for compatibility on safari or other mobile devices?

**Comment by probil** [comment]
Hi @qiangbro 

According to MDN, Safari does support `onbeforeunload` https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

In any case I will check it today.

Thanks for your issue 👍

**Comment by probil** [comment]
@qiangbro it works in Safari on Mac but only in a root frame (doesn't work in `iframe`)

Try this link (without iframe)
https://fiddle.jshell.net/probil/fhmne57w/show/

<img width="1260" alt="Screen Shot 2019-05-21 at 09 34 22" src="https://user-images.githubusercontent.com/6773202/58073589-a9ce3b80-7bab-11e9-8cc3-c3f0dff1748f.png">

**Comment by probil** [comment]
I will check on iOS a well soon

**Comment by probil** [comment]
It seems to be working. I don't thing there is anything I can do to make it work in subframe in safari
